Variabel
Diketahui beberapa list berikut:

ipk = [3.05, 3.45, 3.33, 2.90, 3.10, 3.23, 3.80, 3.74, 3.67, 3.39, 3.41, 3.51, 3.21, 3.55, 3.34, 3.67, 3.77, 3.00, 3.25, 2.78]
sks = [88, 89, 90, 100, 80, 78, 90, 90, 92, 97, 95, 80, 88, 102, 87, 84, 85, 89, 101, 80]
konsentrasi = konsentrasi = ["AK", "AK", "DS", "DS", "AK", "AK", "MK", "MK", "DS", "DS", "IN", "IN", "BS", "BS", "MK", "MK", "BS", "BS", "IN", "IN"]

In [ ]:
# definisi variabel
ipk = [3.05, 3.45, 3.33, 2.90, 3.10, 3.23, 3.80, 3.74, 3.67, 3.39, 3.41, 3.51, 3.21, 3.55, 3.34, 3.67, 3.77, 3.00, 3.25, 2.78]
sks = [88, 89, 90, 100, 80, 78, 90, 90, 92, 97, 95, 80, 88, 102, 87, 84, 85, 89, 101, 80]
konsentrasi = ["AK", "AK", "DS", "DS", "AK", "AK", "MK", "MK", "DS", "DS", "IN", "IN", "BS", "BS", "MK", "MK", "BS", "BS", "IN", "IN"]

In [ ]:
# panjang dari setiap variabel
len(ipk)

20

In [ ]:
# diperoleh nilai mata kuliah baru dengan bobot yang tersimpan dalam variabel bobot berikut
bobot = [3.0, 3.5, 4.0, 4.0, 4.0, 3.0, 3.5, 2.5, 2.8, 2.8, 3.0, 3.5, 3.8, 3.8, 3.8, 2.5, 4.0, 4.0, 3.8, 4.0]
print(bobot)

[3.0, 3.5, 4.0, 4.0, 4.0, 3.0, 3.5, 2.5, 2.8, 2.8, 3.0, 3.5, 3.8, 3.8, 3.8, 2.5, 4.0, 4.0, 3.8, 4.0]


In [ ]:
len(bobot)

20

In [ ]:
# sks mata kuliah tersebut adalah 3. Hitung total bobot dengan mengalikan list bobot dengan 3. Simpan dalam variabel tot_bobot
totalbobot = bobot*3
print(totalbobot)

[3.0, 3.5, 4.0, 4.0, 4.0, 3.0, 3.5, 2.5, 2.8, 2.8, 3.0, 3.5, 3.8, 3.8, 3.8, 2.5, 4.0, 4.0, 3.8, 4.0, 3.0, 3.5, 4.0, 4.0, 4.0, 3.0, 3.5, 2.5, 2.8, 2.8, 3.0, 3.5, 3.8, 3.8, 3.8, 2.5, 4.0, 4.0, 3.8, 4.0, 3.0, 3.5, 4.0, 4.0, 4.0, 3.0, 3.5, 2.5, 2.8, 2.8, 3.0, 3.5, 3.8, 3.8, 3.8, 2.5, 4.0, 4.0, 3.8, 4.0]


In [ ]:
len(totalbobot)

60

package numpy

In [ ]:
import numpy as np

In [ ]:
# Membuat 0-D Array

a = np.array(23)
print(a)

23


In [ ]:
# Membuat 1-D array

b = np.array([1, 4, 6, 9])
print(b)

[1 4 6 9]


In [ ]:
# Membuat 2-D array

c = np.array([[2, 3, 5], [7, 11, 13]])
print(c)

[[ 2  3  5]
 [ 7 11 13]]


In [ ]:
# Membuat 3-D array

d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
# Membuat n-D array dengan numpy.array(array, ndmin = n)

e = np.array([[1, 2, 3], [4, 5, 6]], ndmin = 5)
print(e)

[[[[[1 2 3]
    [4 5 6]]]]]


In [ ]:
# Mengecek dimensi semua array dengan ndim

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)

0
1
2
3
5


indeks array

In [ ]:
# Memanggil elemen pertama pada 1-D array
print(b[0])

1


In [ ]:
# Memanggil array pertama pada 2-D array
arr = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])
print(arr[0])

[11 12 13]


In [ ]:
# Memanggil elemen kedua pada array ketiga 2-D array

print(arr[2, 1])

18


slicing array

Slicing dapat dilakukan dengan menuliskan [mulai : akhir] atau [mulai : akhir : langkah].

Jika mulai tidak dituliskan, maka dianggap 0
Jika akhir tidak dituliskan, maka dianggap hingga panjang array
Jika langkah tidak dituliskan, maka dianggap 1

In [ ]:
arr = np.array([12, 15, 17, 20, 23, 34, 56, 78, 100, 56, 88])

# Mengambil elemen kedua hingga keenam (15, 17, 20, 23, 34)
arr[1:6]

array([15, 17, 20, 23, 34])

In [ ]:
arr = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18], [19, 20, 21]], ndmin=2)

# Mengambil array pertama dan kedua (indeks 0, 1) beserta elemen pertama dan kedua (indeks 0, 1)
arr[0:2, 0:2]

array([[10, 11],
       [13, 14]])

menggabungkan array dngan np.concatenate

In [ ]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([34, 56, 78, 90])

arr = np.concatenate((arr1, arr2))
print(arr)

[ 1  2  3  4 34 56 78 90]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

# Jika axis = 0
arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)

print("\n")

# Jika axis = 1
arr4 = np.concatenate((arr1, arr2), axis=1)
print(arr4)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


[[1 2 5 6]
 [3 4 7 8]]


menggbungkan array dengan stack

In [ ]:
# Cobalah menggabungkan dua array berdimensi 1 berikut dengan stack
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis = 0)

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Coba bandingkan apabila penggabungan dilakukan dengan menggunakan concatenate. Apa yang terjadi?
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2), axis = 0)

print(arr)

[1 2 3 4 5 6]


random

In [ ]:
from numpy import random

In [ ]:
# Merandom bilangan bulat randint(low, high=None, size=None, dtype='l')


x = random.randint(10, 200, size = (4, 3))

print(x)

[[ 26  72  91]
 [128 146  22]
 [ 91  79  84]
 [164  27 196]]


In [ ]:
x.ndim

2

In [ ]:
# Merandom bilangan diantara 0 dan 1 rand(10)
x = random.rand(10)

print(x)

[0.38426937 0.51628766 0.86996551 0.00328265 0.36874509 0.33226681
 0.81611511 0.81985251 0.81120036 0.55553397]


In [ ]:
? random.rand

latihan

In [ ]:
# Variabel tuple dari kasus terkonfirmasi positif dan sembuh
kasus = [[100, 80], [300, 242], [100, 233], [333, 368], [289, 228], [129, 125], [248, 137]]
print(type(kasus))

<class 'list'>


In [ ]:
# ubah list kasus menjadi suatu array, simpan dalam np_kasus
np_kasus = np.array(kasus)
print(np_kasus)

[[100  80]
 [300 242]
 [100 233]
 [333 368]
 [289 228]
 [129 125]
 [248 137]]


In [ ]:
# Berapakah ukuran array kasus?
print(len(kasus))

7


In [ ]:
# tampilkan tuple kasus ke-4
print(kasus[3])

[333, 368]


In [ ]:
# tampilkan semua kasus sembuh
print(kasus)

[[100, 80], [300, 242], [100, 233], [333, 368], [289, 228], [129, 125], [248, 137]]


In [ ]:
# tambahkan kasus terkonfirmasi 190, sembuh 233 pada np_kasus
np.append(np_kasus, [[190, 233]], axis=0)

array([[100,  80],
       [300, 242],
       [100, 233],
       [333, 368],
       [289, 228],
       [129, 125],
       [248, 137],
       [190, 233]])

NUMPY DAN PANDAS by Bu Arum

# prinsip slicing

```
[mulai:akhir]
mulai -> diisikan indeks elemen dimulaina permotongan
akhir -> diisikan indeks akhir pemotongan +1
```

In [1]:
import numpy as np

In [7]:
# melakukan pemotongan indeks ke 1:5
a=np.array([200,400,500,600,700,800,900,100,200])
a[1:5]

array([400, 500, 600, 700])

# Pandas

```
pengolahan data berkaitan dengan data frame
baik membuat data:
1. data tabular
2. membaca data
3. memanipulasi (indexing, slicing, merging, group, dll)
```

In [8]:
import pandas as pd