In [1]:
import pandas as pd

# UTS
fungsi,
numpy (`append, stek, accompenied`),
baris -> `axis=0`,
kolom -> `axis=1`

# Membuat fungsi

In [1]:
import numpy as np

In [9]:
a=np.array([["ibu","ayah","adik"],["sri","widi","yudha"]])
b=np.array([["solo","semarang","bekasi"],['karangpandan',"semarang","bekasi timur"]])

a1=np.concatenate((a,b), axis=1)
print(a1)

print("\n")

a2=np.concatenate((a,b), axis=0)
print(a2)

[['ibu' 'ayah' 'adik' 'solo' 'semarang' 'bekasi']
 ['sri' 'widi' 'yudha' 'karangpandan' 'semarang' 'bekasi timur']]


[['ibu' 'ayah' 'adik']
 ['sri' 'widi' 'yudha']
 ['solo' 'semarang' 'bekasi']
 ['karangpandan' 'semarang' 'bekasi timur']]


In [14]:
a=np.array(["ibu","ayah","adik"])
b=np.array(["solo","semarang","bekasi"])

a2=np.stack((a,b),axis=0)
print(a2)

[['ibu' 'ayah' 'adik']
 ['solo' 'semarang' 'bekasi']]


In [15]:
a=np.array(["ibu","ayah","adik"])
b=np.array(["solo","semarang","bekasi"])

a2=np.concatenate((a,b),axis=0)
print(a2)

['ibu' 'ayah' 'adik' 'solo' 'semarang' 'bekasi']


# LATIHAN STUDI KASUS NUMPY

1. membuat daftar nilai
2. pengolahan nilai dengan max, min, dan average
3. pengurutan nilai dengan ascending dan descending
4. menambah nilai dengan % dan menambah nilai dengan 1

In [1]:
import numpy as np

In [2]:
nilai_siswa = np.array([56,78,98,90,58,64,67,72,93,51])
print(nilai_siswa)

[56 78 98 90 58 64 67 72 93 51]


In [4]:
mean = np.average(nilai_siswa)
print(mean)

72.7


In [9]:
max = np.max(nilai_siswa)
print(max)

low = np.min(nilai_siswa)
print(low)

98
51


In [10]:
# mengetahhui letak index nilai max dan min

print(np.argmax(nilai_siswa))
print(np.argmin(nilai_siswa))


2
9


In [14]:
print(np.sort(nilai_siswa)) # mengurutkan nilai dari terkecil - terbesar
print(-np.sort(-nilai_siswa)) # mengurutkan nilai dari terbesar - terkecil

[51 56 58 64 67 72 78 90 93 98]
[98 93 90 78 72 67 64 58 56 51]


In [17]:
# penambahan nilai sebanyak 10%

nambah_nilai = nilai_siswa*1.1
print(nambah_nilai)

[ 61.6  85.8 107.8  99.   63.8  70.4  73.7  79.2 102.3  56.1]


In [18]:
# penambahan nilai sebanyak 10

nambah_nilai2 = nilai_siswa+10
print(nambah_nilai2)

[ 66  88 108 100  68  74  77  82 103  61]


In [20]:
# penambahan setiap array

print(np.add(nilai_siswa, np.ones(10)))

# outputnya bilangan real, makanya ada titiknya

[57. 79. 99. 91. 59. 65. 68. 73. 94. 52.]


In [21]:
# penambahan setiap array dengan nilai beda setiap array

print(np.add(nilai_siswa, np.array([1,2,3,4,5,6,7,8,9,10])))

[ 57  80 101  94  63  70  74  80 102  61]


# STUDI KASUS FUNCTION

In [24]:
def welcome():
    print("selamat datang, di world tour NCT DREAM")

welcome()
welcome()

selamat datang, di world tour NCT DREAM
selamat datang, di world tour NCT DREAM


In [1]:
def nama(fullname):
    print("Halo fullname welcome to NCT world tour 2022")
    biodata=fullname
    print(fullname, 'welcome to NCT 2022')
nama()

TypeError: nama() missing 1 required positional argument: 'fullname'